### ISSUE TITLE
Why we have created firebase manager class as a singleton?

### ISSUE THREAD

**Issue by anbarasu-seven** [saksham24/Android-Firebase-Mvp-Mvc-Mvvm-chat#1]
Hi, I have a small doubt on firebase manager class that have created in this repository. Actually in in MVP the M represent the data layer of our application, this layer gives the data to the presenter and then it goes to corresponding view as usual. This data layer should have different database reference for different module needs, like "interactor" in [android-mvp-kotlin repository](https://github.com/MindorksOpenSource/android-kotlin-mvp-architecture).  But here we use single database reference for all modules, which is the correct way of using data layer reference.

**Comment by saksham24** [comment]
**Consider Firebase Operations as Network not Model.**
Don't be confused with FirebaseDatabaseReference as this is **not data model reference** which we call "**M" in MVP**. FirebaseDatabase is remote database just as what we call an API  from the server. For this repository, Firebase is NoSQL remote server to store and get data. Anything out of your application cannot be considered as Model. Building a data layer will be a good option which I am going to build soon when I will add a local database in the app but again I say firebase manager is getting messages from the remote database which may be considered as getting data from any server using API so making such instance singleton is a good choice. For me, every class which does now have much significance in its object's creation should be a singleton.

**Comment by anbarasu-seven** [comment]
You are not created your data layer so not concentrating much on where to put firebase listener. Consider I created a data layer and I keep on using that data layer instance in presenter. That data layer has different references inside it, ex. PreferenceManger, RealmDbManager, NetworkApiManager and AssetManager(for testing only). Whenever presenter receive any request from view that will be given to corresponding data layer, that data layer will decide where to get the data( from PreferenceManger/RealmDbManager/NetworkApiManager/......)to satisfy the request. Now you got any idea to place your firebase data listener. What i thought is firebase also return some data so that should be handled in data layer.

**Comment by saksham24** [comment]
You are right in my project data layer is missing which I will add in a couple of days in all examples including MVC and MVVM. As I will implement local database so I will be in need of a data layer now.
Soon I am going to commit Kotlin- Mvvm and after that, I have to focus on the local database including data layer.  Thanks for the suggestion I will update it soon. Also, I welcome you to contribute your knowledge to the project if you can. Implementation of data layer in java or kotlin (MVP) Projects will be accepted as a merge request. Thanks @anbarasu-seven
