### ISSUE TITLE
In chat mvp java there is a missing attribute in EdtText field.

### ISSUE THREAD

**Issue by ShubhamRaj1997** [saksham24/Android-Firebase-Mvp-Mvc-Mvvm-chat#2]
we can add inputType attribute to the EditText field with id "edittext_chat_message" by adding line "android:inputType="text""

**Comment by saksham24** [comment]
Significance of doing so?

**Comment by saksham24** [comment]
Significance of adding it?

**Comment by saksham24** [comment]
This was a senseless issue opened. Sorry please be little active after opening issues as you were before opening it.
